sentence = input()
cleaned = sentence.strip()
normalized = cleaned.lower().replace('.', '')
words = normalized.split()
slug = "-".join(words)
uppercase_str = normalized.upper()
python_pos = normalized.find("python")

print(f"Cleaned: {cleaned}")
print(f"Normalized: {normalized}")
print(f"Words: {words}")
print(f"Slug: {slug}")
print(f"Uppercase: {uppercase_str}")
print(f"Python Position: {python_pos}")